In [1]:
import pandas as pd

In [3]:
from sklearn.ensemble import RandomForestClassifier

In [9]:
!pip install openpyxl

Requirement already satisfied: openpyxl in c:\users\anshika\anaconda3\envs\booksenv\lib\site-packages (3.0.9)
Requirement already satisfied: et-xmlfile in c:\users\anshika\anaconda3\envs\booksenv\lib\site-packages (from openpyxl) (1.1.0)

In [29]:
import pandas as pd

df = pd.read_excel("iris_train.xlsx", engine="openpyxl")


df.head()

    sepal length  sepal width  petal length  petal width        Class
0            5.1          3.5           1.4          0.2  Iris-setosa
1            4.9          3.0           1.4          0.2  Iris-setosa
2            4.7          3.2           1.3          0.2  Iris-setosa
3            4.6          3.1           1.5          0.2  Iris-setosa
4            5.0          3.6           1.4          0.2  Iris-setosa

In [31]:
x = df.iloc[:,:-1]

In [33]:
x

      sepal length  sepal width  petal length  petal width
0              5.1          3.5           1.4          0.2
1              4.9          3.0           1.4          0.2
2              4.7          3.2           1.3          0.2
3              4.6          3.1           1.5          0.2
4              5.0          3.6           1.4          0.2
..             ...          ...           ...          ...
145            6.7          3.0           5.2          2.3
146            6.3          2.5           5.0          1.9
147            6.5          3.0           5.2          2.0
148            6.2          3.4           5.4          2.3
149            5.9          3.0           5.1          1.8

[150 rows x 4 columns]

In [35]:
y = df.iloc[:,-1]

In [37]:
y

0         Iris-setosa
1         Iris-setosa
2         Iris-setosa
3         Iris-setosa
4         Iris-setosa
            ...
145    Iris-virginica
146    Iris-virginica
147    Iris-virginica
148    Iris-virginica
149    Iris-virginica
Name: Class, Length: 150, dtype: object

In [39]:
model = RandomForestClassifier()

In [41]:
model.fit(x.values,y.values)

RandomForestClassifier()

In [49]:
predict = model.predict([[5.4, 3.9, 1.3, 0.4]])

In [51]:
predict

array(['Iris-setosa'], dtype=object)

In [53]:
datatest = pd.read_excel("iris_test.xlsx",engine = "openpyxl")

In [55]:
x_test = datatest.iloc[:,:-1]

In [57]:
predict = model.predict(x_test.values)

In [59]:
predict

array(['Iris-versicolor', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-versicolor', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-virginica', 'Iris-versicolor', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa'], dtype=object)